import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  contentContainer: {
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logoCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#E0232A",
    justifyContent: "center",
    alignItems: "center",
  },
  logoText: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "bold",
  },
  headerTitle: {
    color: "#FFF",
    fontSize: 16,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  loginButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  loginButtonText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "500",
  },
  heroSection: {
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 60,
    minHeight: 400,
    justifyContent: "flex-end",
  },
  heroContent: {
    zIndex: 1,
  },
  heroTag: {
    color: "#E0232A",
    fontSize: 12,
    letterSpacing: 2,
    fontWeight: "600",
    marginBottom: 16,
  },
  heroTitle: {
    color: "#FFF",
    fontSize: 48,
    fontWeight: "700",
    fontStyle: "italic",
    lineHeight: 52,
    marginBottom: 16,
  },
  heroSubtitle: {
    color: "#AAA",
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 24,
  },
  heroButtonsRow: {
    flexDirection: "row",
    gap: 12,
  },
  exploreButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 24,
    gap: 8,
  },
  exploreButtonText: {
    color: "#000",
    fontWeight: "600",
    fontSize: 16,
  },
  enterNationButton: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 24,
  },
  enterNationButtonText: {
    color: "#FFF",
    fontWeight: "600",
    fontSize: 16,
  },
  section: {
    marginTop: 20,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionTitle: {
    color: "#FFF",
    fontSize: 20,
    fontWeight: "600",
    marginBottom: 4,
  },
  sectionSubtitle: {
    color: "#888",
    fontSize: 14,
  },
  seeAll: {
    color: "#888",
    fontSize: 14,
  },
  horizontalScroll: {
    paddingLeft: 20,
  },
  card: {
    width: 160,
    backgroundColor: "#111",
    borderRadius: 16,
    padding: 12,
    marginRight: 16,
    borderWidth: 1,
    borderColor: "#222",
  },
  smallCard: {
    width: 140,
    backgroundColor: "#111",
    borderRadius: 16,
    padding: 12,
    marginRight: 16,
    borderWidth: 1,
    borderColor: "#222",
  },
  imagePlaceholder: {
    width: "100%",
    height: 160,
    backgroundColor: "#222",
    borderRadius: 8,
    marginBottom: 12,
  },
  tagBadge: {
    position: "absolute",
    top: 20,
    left: 20,
    backgroundColor: "#E0232A",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    zIndex: 1,
  },
  tagBadgeText: {
    color: "#FFF",
    fontSize: 10,
    fontWeight: "bold",
  },
  cardTitle: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 8,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardPrice: {
    color: "#888",
    fontSize: 14,
  },
  addButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
  },
  largeCard: {
    marginHorizontal: 20,
    backgroundColor: "#111",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#222",
  },
  categoryText: {
    color: "#888",
    fontSize: 12,
    letterSpacing: 1,
    marginBottom: 4,
  },
  largeCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  largeCardTitle: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 4,
  },
  largeCardPrice: {
    color: "#E0232A",
    fontSize: 16,
    fontWeight: "600",
  },
  accordionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: "#222",
    marginHorizontal: 20,
    marginBottom: 8,
    borderRadius: 12,
    backgroundColor: "#0A0A0A",
  },
  accordionText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "500",
  },
  premiumCard: {
    padding: 24,
    borderRadius: 16,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: "#500A10",
  },
  premiumTag: {
    color: "#E0232A",
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: "bold",
    marginBottom: 12,
  },
  premiumTitle: {
    color: "#FFF",
    fontSize: 24,
    fontWeight: "600",
    marginBottom: 8,
  },
  premiumSubtitle: {
    color: "#AAA",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
  },
  premiumButton: {
    backgroundColor: "#FFF",
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: "center",
  },
  premiumButtonText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "600",
  },
});
